// SPDX-FileCopyrightText: 2022 The Manyverse Authors
//
// SPDX-License-Identifier: MPL-2.0

/**
 * This object assigns meaning in the context of Manyverse for the icon names
 * we use from MaterialCommunityIcons, in order to have consistent icons for
 * each meaning.
 */
export const IconNames = {
  selected: 'check-circle',
  audioPause: 'pause',
  audioPlay: 'play',
  audioRecord: 'microphone',
  audioStop: 'stop',
  backButton: 'arrow-left',
  backButtonIOS: 'chevron-left',
  hamburgerMenu: 'menu',
  roomAliasLink: 'link-variant',
  delete: 'delete',
  etc: 'dots-horizontal',
  etcDropdown: 'dots-vertical',
  copyToClipboard: 'content-copy',
  accountFollow: 'account-plus',
  accountBlock: 'account-remove',
  accountUnfollow: 'account-minus',
  accountUnblock: 'account-minus',
  friendsInCommon: 'account-heart',
  contentWarning: 'alert',
  addReaction: 'emoticon-happy-outline',
  threadComment: 'comment-outline',
  activity: 'bell-outline',
  activityActive: 'bell-ring-outline',
  connectionsOffline: 'circle-medium',
  connectionsBad: 'speedometer-slow',
  connectionsFair: 'speedometer-medium',
  connectionsGood: 'speedometer',
  privateChat: 'message-outline',
  privateChatActive: 'message-text-outline',
  publicFeed: 'bulletin-board',
  error: 'alert-circle-outline',
  success: 'check-bold',
  peerBluetooth: 'bluetooth',
  peerWifi: 'wifi',
  peerInternetServer: 'server-network',
  peerInternetDirect: 'account-network',
  peerUnknown: 'help-network',
  mention: 'at',
  connectionNew: 'plus-network',
  aloneOrOffline: 'circle-outline',
  search: 'magnify',
  takePicture: 'camera',
  attachPicture: 'image',
  compose: 'pencil',
  enterFullScreen: 'arrow-expand',
  exitFullScreen: 'arrow-collapse',
  sendMessage: 'send',
  listOfPeople: 'account-multiple',
  versionUpdate: 'update',
  settings: 'cog',
  myProfile: 'account-circle',
  rawDatabase: 'database',
  emailBugReport: 'email-alert',
  contributeTranslations: 'translate',
  scrollToSeeMore: 'chevron-down',
  openInNewWindow: 'open-in-new',
  storage: 'sd',
  searchAccounts: 'account-search',
  clearTextInput: 'close',
  clearTextInputIOS: 'close-circle',
  separatorDot: 'circle-small',
};
