platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'Manyverse' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # FIXME: Can we delete this? See https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#remove-rnn-pod-from-podspec
  # pod 'ReactNativeNavigation', :podspec => '../node_modules/react-native-navigation/ReactNativeNavigation.podspec'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'RNOS', :podspec => '../node_modules/react-native-os-staltz/RNOS.podspec'
  pod 'RCTSystemSetting', :path => '../node_modules/react-native-system-setting'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'
  pod 'RNLocalize', :path => '../node_modules/react-native-localize'
  pod 'ReactNativeAudioToolkit', :path => '../node_modules/@react-native-community/audio-toolkit'

  target 'ManyverseTests' do
    inherit! :complete
    # Pods for testing
  end

  use_frameworks!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'Manyverse-tvOS' do
  # Pods for Manyverse-tvOS
  target 'Manyverse-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end