// SPDX-FileCopyrightText: 2020-2022 The Manyverse Authors
//
// SPDX-License-Identifier: MPL-2.0

export enum Screens {
  Welcome = 'Manyverse.Welcome',
  Migrating = 'Manyverse.Migrating',
  Central = 'Manyverse.Central',
  Drawer = 'Manyverse.Drawer',
  DialogAbout = 'Manyverse.Dialog.About',
  DialogThanks = 'Manyverse.Dialog.Thanks',
  Compose = 'Manyverse.Compose',
  ComposeAudio = 'Manyverse.Compose.Audio',
  ConnectionsPanel = 'Manyverse.ConnectionsPanel',
  Search = 'Manyverse.Search',
  Thread = 'Manyverse.Thread',
  Conversation = 'Manyverse.Conversation',
  RecipientsInput = 'Manyverse.RecipientsInput',
  Libraries = 'Manyverse.Libraries',
  InvitePaste = 'Manyverse.Invite.Paste',
  Profile = 'Manyverse.Profile',
  ProfileEdit = 'Manyverse.Profile.Edit',
  AliasManage = 'Manyverse.Alias.Manage',
  AliasRegister = 'Manyverse.Alias.Register',
  Biography = 'Manyverse.Biography',
  Accounts = 'Manyverse.Accounts',
  Backup = 'Manyverse.Backup',
  Instructions = 'Manyverse.Instructions',
  SecretOutput = 'Manyverse.SecretOutput',
  SecretInput = 'Manyverse.SecretInput',
  Resync = 'Manyverse.Resync',
  RawDatabase = 'Manyverse.RawDatabase',
  RawMessage = 'Manyverse.RawMessage',
  Settings = 'Manyverse.Settings',
  Storage = 'Manyverse.Storage',
  Compact = 'Manyverse.Compact',
  Indexing = 'Manyverse.Indexing',
  FeedSettings = 'Manyverse.FeedSettings',
}
