/* Any copyright is dedicated to the Public Domain.
 * http://creativecommons.org/publicdomain/zero/1.0/ */

export default [
  {
    name: 'noun-crops.png',
    author: "'Made by Made' from the Noun Project",
    license: 'Creative Commons BY 3.0',
    homepage: 'https://thenounproject.com/term/crops/1042090',
    type: 'image',
  },
  {
    name: 'noun-lantern.png',
    author: "'Made by Made' from the Noun Project",
    license: 'Creative Commons BY 3.0',
    homepage: 'https://thenounproject.com/term/lantern/816093',
    type: 'image',
  },
  {
    name: 'noun-plant.png',
    author: "'Made by Made' from the Noun Project",
    license: 'Creative Commons BY 3.0',
    homepage: 'https://thenounproject.com/term/plant/712811',
    type: 'image',
  },
  {
    name: 'noun-books.png',
    author: "'Made by Made, AU' from the Noun Project",
    license: 'Creative Commons BY 3.0',
    homepage: 'https://thenounproject.com/term/books/1029325',
    type: 'image',
  },
  {
    name: 'noun-glassware.png',
    author: "'Made by Made, AU' from the Noun Project",
    license: 'Creative Commons BY 3.0',
    homepage: 'https://thenounproject.com/term/glassware/815762/',
    type: 'image',
  },
  {
    name: 'noun-fingerprint.png',
    author: "'icon 54' from the Noun Project",
    license: 'Creative Commons BY 3.0',
    homepage: 'https://thenounproject.com/term/Fingerprint/412008/',
    type: 'image',
  },
  {
    name: 'noun-butterfly.png',
    author: "'Made by Made, AU' from the Noun Project",
    license: 'Creative Commons BY 3.0',
    homepage: 'https://thenounproject.com/term/butterfly/1214207/',
    type: 'image',
  },
  {
    name: 'noun-roots.png',
    author: "'IYIKON, PK' from the Noun Project",
    license: 'Creative Commons BY 3.0',
    homepage: 'https://thenounproject.com/term/roots/1544184/',
    type: 'image',
  },
  {
    name: 'noun-camping.png',
    author: "'Made by Made, AU' from the Noun Project",
    license: 'Creative Commons BY 3.0',
    homepage: 'https://thenounproject.com/term/camping/964076/',
    type: 'image',
  },
  {
    name: 'noun-fish.png',
    author: "'Made by Made, AU' from the Noun Project",
    license: 'Creative Commons BY 3.0',
    homepage: 'https://thenounproject.com/term/fish/1782166/',
    type: 'image',
  },
  {
    name: 'noun-farm.png',
    author: "'Made by Made, AU' from the Noun Project",
    license: 'Creative Commons BY 3.0',
    homepage: 'https://thenounproject.com/term/farm/1724818/',
    type: 'image',
  },
  {
    name: 'noun-wheelbarrow.png',
    author: "'Made by Made, AU' from the Noun Project",
    license: 'Creative Commons BY 3.0',
    homepage: 'https://thenounproject.com/term/wheel-barrow/1042083/',
    type: 'image',
  },
  {
    name: 'noun-flower.png',
    author: "'Made by Made, AU' from the Noun Project",
    license: 'Creative Commons BY 3.0',
    homepage: 'https://thenounproject.com/term/flower/712816/',
    type: 'image',
  },
  {
    name: '@cycle/isolate',
    type: 'library',
    version: '5.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://cycle.js.org',
  },
  {
    name: '@cycle/react',
    type: 'library',
    version: '2.7.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/cyclejs/react',
  },
  {
    name: '@cycle/react-dom',
    type: 'library',
    version: '2.4.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/cyclejs/react-dom',
  },
  {
    name: '@cycle/react-native',
    type: 'library',
    version: '2.0.0',
    license: 'MIT License (MIT)',
  },
  {
    name: '@cycle/run',
    type: 'library',
    version: '5.5.0',
    license: 'MIT License (MIT)',
    homepage: 'https://cycle.js.org',
  },
  {
    name: '@cycle/state',
    type: 'library',
    version: '1.4.0',
    license: 'MIT License (MIT)',
    homepage: 'https://cycle.js.org',
  },
  {
    name: '@react-native-community/art',
    type: 'library',
    version: '1.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/react-native-community/react-native-art',
  },
  {
    name: '@react-native-community/audio-toolkit',
    type: 'library',
    version: '2.0.3',
    license: 'MIT License (MIT)',
    homepage:
      'https://github.com/react-native-community/react-native-audio-toolkit#readme',
  },
  {
    name: '@react-native-community/slider',
    type: 'library',
    version: '2.0.8',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/react-native-community/react-native-slider',
  },
  {
    name: '@react-native-community/viewpager',
    type: 'library',
    version: '3.1.0',
    license: 'MIT License (MIT)',
    homepage:
      'https://github.com/react-native-community/react-native-viewpager#readme',
  },
  {
    name: 'bindings-noderify-nodejs-mobile',
    type: 'library',
    version: '10.3.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/bindings-noderify-nodejs-mobile',
  },
  {
    name: 'buffer',
    type: 'library',
    version: '5.6.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/feross/buffer',
  },
  {
    name: 'bufferutil',
    type: 'library',
    version: '4.0.1',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/websockets/bufferutil',
  },
  {
    name: 'cached-path-relative',
    type: 'library',
    version: '1.0.2',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ashaffer/cached-path-relative#readme',
  },
  {
    name: 'chloride',
    type: 'library',
    version: '2.4.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/dominictarr/chloride#readme',
  },
  {
    name: 'color-hash',
    type: 'library',
    version: '1.0.3',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/zenozeng/color-hash#readme',
  },
  {
    name: 'cycle-native-alert',
    type: 'library',
    version: '1.1.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/cycle-native-alert#readme',
  },
  {
    name: 'cycle-native-android-local-notification',
    type: 'library',
    version: '1.1.0',
    license: 'MIT License (MIT)',
    homepage:
      'https://gitlab.com/staltz/cycle-native-android-local-notification#readme',
  },
  {
    name: 'cycle-native-asyncstorage',
    type: 'library',
    version: '3.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/cycle-native-asyncstorage#readme',
  },
  {
    name: 'cycle-native-clipboard',
    type: 'library',
    version: '1.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/cycle-native-clipboard#readme',
  },
  {
    name: 'cycle-native-keyboard',
    type: 'library',
    version: '1.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/cycle-native-keyboard#readme',
  },
  {
    name: 'cycle-native-linking',
    type: 'library',
    version: '1.1.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/cycle-native-linking#readme',
  },
  {
    name: 'cycle-native-navigation',
    type: 'library',
    version: '7.8.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/cycle-native-navigation',
  },
  {
    name: 'cycle-native-share',
    type: 'library',
    version: '1.1.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/cycle-native-share#readme',
  },
  {
    name: 'cycle-native-toastandroid',
    type: 'library',
    version: '1.1.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/cycle-native-toastandroid#readme',
  },
  {
    name: 'electron',
    type: 'library',
    version: '10.1.3',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/electron/electron#readme',
  },
  {
    name: 'electron-ssb-client',
    type: 'library',
    version: '1.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/electron-ssb-client',
  },
  {
    name: 'faucet',
    type: 'library',
    version: '0.0.1',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/substack/faucet',
  },
  {
    name: 'hermes-engine',
    type: 'library',
    version: '0.5.2-rc1',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/facebook/hermes#readme',
  },
  {
    name: 'i18n-js',
    type: 'library',
    version: '3.7.1',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/fnando/i18n-js',
  },
  {
    name: 'ip',
    type: 'library',
    version: '1.1.5',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/indutny/node-ip',
  },
  {
    name: 'leveldown-nodejs-mobile',
    type: 'library',
    version: '5.4.1-1',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/leveldown-nodejs-mobile',
  },
  {
    name: 'lodash.memoize',
    type: 'library',
    version: '4.1.2',
    license: 'MIT License (MIT)',
    homepage: 'https://lodash.com/',
  },
  {
    name: 'mdast-normalize-react-native',
    type: 'library',
    version: '3.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/mdast-normalize-react-native#readme',
  },
  {
    name: 'mkdirp',
    type: 'library',
    version: '1.0.4',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/isaacs/node-mkdirp#readme',
  },
  {
    name: 'multiserver-electron-ipc',
    type: 'library',
    version: '1.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/multiserver-electron-ipc#readme',
  },
  {
    name: 'multiserver-rn-channel',
    type: 'library',
    version: '1.3.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/multiserver-rn-channel#readme',
  },
  {
    name: 'nodejs-mobile-react-native',
    type: 'library',
    version: '0.6.2',
    license: 'MIT License (MIT)',
    homepage: 'https://code.janeasystems.com/nodejs-mobile',
  },
  {
    name: 'non-private-ip-android',
    type: 'library',
    version: '1.4.4-3',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/non-private-ip',
  },
  {
    name: 'path',
    type: 'library',
    version: '0.12.7',
    license: 'MIT License (MIT)',
    homepage: 'http://nodejs.org/docs/latest/api/path.html',
  },
  {
    name: 'promisify-tuple',
    type: 'library',
    version: '1.0.1',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/promisify-tuple#readme',
  },
  {
    name: 'pull-async',
    type: 'library',
    version: '1.0.0',
    license: 'Apache License 2.0 (Apache-2.0)',
    homepage: 'https://github.com/ahdinosaur/pull-async#readme',
  },
  {
    name: 'pull-backoff',
    type: 'library',
    version: '1.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/pull-backoff#readme',
  },
  {
    name: 'pull-cat',
    type: 'library',
    version: '1.1.11',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/pull-stream/pull-cat',
  },
  {
    name: 'pull-combine-latest',
    type: 'library',
    version: '1.1.2',
    license: 'ISC License (ISC)',
    homepage: 'https://github.com/nichoth/pull-combine-latest#readme',
  },
  {
    name: 'pull-file',
    type: 'library',
    version: '1.1.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/DamonOehlman/pull-file',
  },
  {
    name: 'pull-flat-list',
    type: 'library',
    version: '2.14.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/pull-flat-list',
  },
  {
    name: 'pull-pair',
    type: 'library',
    version: '1.1.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/dominictarr/pull-pair',
  },
  {
    name: 'pull-pushable',
    type: 'library',
    version: '2.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/dominictarr/pull-pushable',
  },
  {
    name: 'pull-stream',
    type: 'library',
    version: '3.6.14',
    license: 'MIT License (MIT)',
    homepage: 'https://pull-stream.github.io',
  },
  {
    name: 'pull-stream-util',
    type: 'library',
    version: '0.1.2',
    license: 'ISC License (ISC)',
    homepage: 'https://github.com/nichoth/pull-stream-util#readme',
  },
  {
    name: 'pull-switch-map',
    type: 'library',
    version: '1.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/pull-switch-map#readme',
  },
  {
    name: 'pull-thenable',
    type: 'library',
    version: '1.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/pull-thenable',
  },
  {
    name: 'react',
    type: 'library',
    version: '16.13.1',
    license: 'MIT License (MIT)',
    homepage: 'https://reactjs.org/',
  },
  {
    name: 'react-dom',
    type: 'library',
    version: '16.13.1',
    license: 'MIT License (MIT)',
    homepage: 'https://reactjs.org/',
  },
  {
    name: 'react-markdown',
    type: 'library',
    version: '4.0.2',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/rexxars/react-markdown#readme',
  },
  {
    name: 'react-native',
    type: 'library',
    version: '0.63.3',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/facebook/react-native#readme',
  },
  {
    name: 'react-native-bluetooth-socket-bridge',
    type: 'library',
    version: '1.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/Happy0/react-native-bluetooth-socket-bridge/',
  },
  {
    name: 'react-native-dialogs',
    type: 'library',
    version: '1.1.1',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/aakashns/react-native-dialogs#readme',
  },
  {
    name: 'react-native-emoji-picker-staltz',
    type: 'library',
    version: '0.2.2',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/react-native-emoji-picker',
  },
  {
    name: 'react-native-flag-secure-android',
    type: 'library',
    version: '1.0.2',
    license: 'ISC License (ISC)',
    homepage:
      'https://github.com/staltz/react-native-flag-secure-android#readme',
  },
  {
    name: 'react-native-floating-action',
    type: 'library',
    version: '1.21.0',
    license: 'MIT License (MIT)',
    homepage:
      'https://github.com/santomegonzalo/react-native-floating-action#readme',
  },
  {
    name: 'react-native-fs',
    type: 'library',
    version: '2.16.6',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/itinance/react-native-fs#readme',
  },
  {
    name: 'react-native-gifted-chat',
    type: 'library',
    version: '0.16.3',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/FaridSafi/react-native-gifted-chat#readme',
  },
  {
    name: 'react-native-has-internet',
    type: 'library',
    version: '4.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/react-native-has-internet',
  },
  {
    name: 'react-native-image-crop-picker',
    type: 'library',
    version: '0.26.1',
    license: 'MIT License (MIT)',
    homepage:
      'https://github.com/ivpusic/react-native-image-crop-picker#readme',
  },
  {
    name: 'react-native-image-viewing',
    type: 'library',
    version: '0.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/jobtoday/react-native-image-viewing#readme',
  },
  {
    name: 'react-native-localize',
    type: 'library',
    version: '1.4.1',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/react-native-community/react-native-localize',
  },
  {
    name: 'react-native-navigation',
    type: 'library',
    version: '6.12.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/wix/react-native-navigation',
  },
  {
    name: 'react-native-orientation-locker',
    type: 'library',
    version: '1.1.7',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/wonday/react-native-orientation-locker',
  },
  {
    name: 'react-native-popup-menu',
    type: 'library',
    version: '0.15.6',
    license: 'ISC License (ISC)',
    homepage: 'https://github.com/instea/react-native-popup-menu',
  },
  {
    name: 'react-native-progress',
    type: 'library',
    version: '4.1.2',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/oblador/react-native-progress',
  },
  {
    name: 'react-native-splash-screen',
    type: 'library',
    version: '3.2.0',
    license: 'MIT License (MIT)',
    homepage:
      'https://github.com/crazycodeboy/react-native-splash-screen#readme',
  },
  {
    name: 'react-native-ssb-client',
    type: 'library',
    version: '7.1.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/react-native-ssb-client',
  },
  {
    name: 'react-native-ssb-shims',
    type: 'library',
    version: '5.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/react-native-ssb-shims',
  },
  {
    name: 'react-native-status-bar-height',
    type: 'library',
    version: '2.5.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ovr/react-native-status-bar-height#readme',
  },
  {
    name: 'react-native-swiper',
    type: 'library',
    version: '1.5.14',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/leecade/react-native-swiper#readme',
  },
  {
    name: 'react-native-system-setting',
    type: 'library',
    version: '1.7.5',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/c19354837/react-native-system-setting',
  },
  {
    name: 'react-native-tiny-toast',
    type: 'library',
    version: '1.0.4',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/shx996/react-native-tiny-toast#readme',
  },
  {
    name: 'react-native-vector-icons',
    type: 'library',
    version: '6.6.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/oblador/react-native-vector-icons',
  },
  {
    name: 'react-native-web',
    type: 'library',
    version: '0.14.10',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/necolas/react-native-web#readme',
  },
  {
    name: 'react-propify-methods',
    type: 'library',
    version: '16.3.2',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/react-propify-methods',
  },
  {
    name: 'react-xstream-hoc',
    type: 'library',
    version: '1.1.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/react-xstream-hoc',
  },
  {
    name: 'remark',
    type: 'library',
    version: '9.0.0',
    license: 'MIT License (MIT)',
    homepage: 'http://remark.js.org',
  },
  {
    name: 'remark-gemoji-to-emoji',
    type: 'library',
    version: '1.1.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/jackycute/remark-gemoji-to-emoji#readme',
  },
  {
    name: 'remark-images-to-ssb-serve-blobs',
    type: 'library',
    version: '2.1.0-1',
    license: 'MIT License (MIT)',
    homepage:
      'https://gitlab.com/staltz/remark-images-to-ssb-serve-blobs#readme',
  },
  {
    name: 'remark-linkify-regex',
    type: 'library',
    version: '1.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/remark-linkify-regex#readme',
  },
  {
    name: 'remark-ssb-mentions',
    type: 'library',
    version: '2.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/ssb-mentions',
  },
  {
    name: 'rimraf',
    type: 'library',
    version: '3.0.2',
    license: 'ISC License (ISC)',
    homepage: 'https://github.com/isaacs/rimraf#readme',
  },
  {
    name: 'secret-stack',
    type: 'library',
    version: '6.3.2',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/secret-stack',
  },
  {
    name: 'sodium-chloride-native-nodejs-mobile',
    type: 'library',
    version: '1.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/sodium-chloride-native-nodejs-mobile',
  },
  {
    name: 'ssb-about',
    type: 'library',
    version: '2.0.1',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/ssb-about',
  },
  {
    name: 'ssb-blobs',
    type: 'library',
    version: '1.2.2',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/ssb-blobs',
  },
  {
    name: 'ssb-blobs-purge',
    type: 'library',
    version: '1.0.1',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/ssb-blobs-purge',
  },
  {
    name: 'ssb-bluetooth',
    type: 'library',
    version: '1.1.14',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/happy0/ssb-bluetooth#readme',
  },
  {
    name: 'ssb-caps',
    type: 'library',
    version: '1.1.0',
    license: 'Creative Commons Zero v1.0 Universal (CC0-1.0)',
    homepage: 'https://github.com/ssbc/ssb-caps#readme',
  },
  {
    name: 'ssb-config',
    type: 'library',
    version: '3.4.5',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/ssb-config',
  },
  {
    name: 'ssb-conn',
    type: 'library',
    version: '2.0.2',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/ssb-conn',
  },
  {
    name: 'ssb-conn-query',
    type: 'library',
    version: '1.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/ssb-conn-query',
  },
  {
    name: 'ssb-db2',
    type: 'library',
    version: '1.18.5',
    license: 'GNU Lesser General Public License v3.0 only (LGPL-3.0)',
    homepage: 'https://github.com/ssb-ngi-pointer/ssb-db2',
  },
  {
    name: 'ssb-deweird',
    type: 'library',
    version: '1.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/ssb-deweird',
  },
  {
    name: 'ssb-dht-invite',
    type: 'library',
    version: '1.12.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/ssb-dht-invite#readme',
  },
  {
    name: 'ssb-ebt',
    type: 'library',
    version: '6.0.0-rc1',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/ssb-ebt',
  },
  {
    name: 'ssb-friends',
    type: 'library',
    version: '4.4.4',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/ssb-friends',
  },
  {
    name: 'ssb-invite-client',
    type: 'library',
    version: '1.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/ssb-invite-client',
  },
  {
    name: 'ssb-keys',
    type: 'library',
    version: '8.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/ssb-keys',
  },
  {
    name: 'ssb-keys-mnemonic',
    type: 'library',
    version: '1.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/ssb-keys-mnemonic',
  },
  {
    name: 'ssb-keys-mnemonic-neon',
    type: 'library',
    version: '1.0.0-2',
    license: 'GNU Affero General Public License v3.0 (AGPL-3.0)',
    homepage: 'https://github.com/staltz/ssb-keys-mnemonic-neon#readme',
  },
  {
    name: 'ssb-keys-neon',
    type: 'library',
    version: '8.0.0-8',
    license: 'GNU Affero General Public License v3.0 (AGPL-3.0)',
    homepage: 'https://github.com/staltz/ssb-keys-neon#readme',
  },
  {
    name: 'ssb-lan',
    type: 'library',
    version: '1.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/ssb-lan',
  },
  {
    name: 'ssb-master',
    type: 'library',
    version: '1.0.3',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/ssb-master#readme',
  },
  {
    name: 'ssb-mobile-bluetooth-manager',
    type: 'library',
    version: '3.2.3',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/ssb-mobile-bluetooth-manager#readme',
  },
  {
    name: 'ssb-ref',
    type: 'library',
    version: '2.13.9',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/ssb-ref',
  },
  {
    name: 'ssb-replicate',
    type: 'library',
    version: '1.3.2',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/dominictarr/ssb-replicate',
  },
  {
    name: 'ssb-room-client',
    type: 'library',
    version: '0.2.0',
    license: 'GNU Lesser General Public License v3.0 only (LGPL-3.0)',
    homepage: 'https://github.com/ssb-ngi-pointer/ssb-room-client',
  },
  {
    name: 'ssb-serve-blobs',
    type: 'library',
    version: '2.5.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/ssb-serve-blobs',
  },
  {
    name: 'ssb-suggest-lite',
    type: 'library',
    version: '1.0.3',
    license: 'GNU Lesser General Public License v3.0 only (LGPL-3.0)',
    homepage: 'https://github.com/ssb-ngi-pointer/ssb-suggest-lite#readme',
  },
  {
    name: 'ssb-threads',
    type: 'library',
    version: '7.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/ssb-threads#readme',
  },
  {
    name: 'ssb-typescript',
    type: 'library',
    version: '2.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/ssbc/ssb-typescript#readme',
  },
  {
    name: 'staltz-multiserver',
    type: 'library',
    version: '3.3.6-1',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/multiserver',
  },
  {
    name: 'utf-8-validate',
    type: 'library',
    version: '5.0.3',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/websockets/utf-8-validate',
  },
  {
    name: 'utp-native-nodejs-mobile',
    type: 'library',
    version: '2.1.3-1',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/utp-native-nodejs-mobile#readme',
  },
  {
    name: 'xstream',
    type: 'library',
    version: '11.13.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/xstream#readme',
  },
  {
    name: 'xstream-between',
    type: 'library',
    version: '1.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/xstream-between#readme',
  },
  {
    name: 'xstream-drop-repeats-by-keys',
    type: 'library',
    version: '1.1.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/xstream-drop-repeats-by-keys#readme',
  },
  {
    name: 'xstream-from-callback',
    type: 'library',
    version: '1.1.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/xstream-from-callback',
  },
  {
    name: 'xstream-from-pull-stream',
    type: 'library',
    version: '1.2.0',
    license: 'MIT License (MIT)',
    homepage: 'https://github.com/staltz/xstream-from-pull-stream',
  },
  {
    name: 'xstream-sample',
    type: 'library',
    version: '1.0.0',
    license: 'MIT License (MIT)',
    homepage: 'https://gitlab.com/staltz/xstream-sample#readme',
  },
];
