#!/bin/bash

# Any copyright is dedicated to the Public Domain.
# http://creativecommons.org/publicdomain/zero/1.0/

set -eEu -o pipefail
shopt -s extdebug
IFS=$'\n\t'
trap 'onFailure $?' ERR

function onFailure() {
  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
  exit 1
}

SECONDS=0
echo -en "Compiling TypeScript...";
npm run --silent lib;
echo -en " — $SECONDS s\n";

SECONDS=0
echo -en "Setting up...";
mkdir -p ./nodejs-assets;
rm -rf ./nodejs-assets/nodejs-project;
if [ -f ./nodejs-assets/BUILD_NATIVE_MODULES.txt ]
then
  echo -en " Build Native Modules already on";
else
  echo '1' >./nodejs-assets/BUILD_NATIVE_MODULES.txt;
  echo -en " Build Native Modules turned on";
fi
cp -r ./lib/backend ./nodejs-assets;
mv ./nodejs-assets/backend ./nodejs-assets/nodejs-project;
cp ./src/backend/package.json ./nodejs-assets/nodejs-project;
cp ./src/backend/package-lock.json ./nodejs-assets/nodejs-project;
rm ./nodejs-assets/nodejs-project/*.js.map;
rm ./nodejs-assets/nodejs-project/plugins/*.js.map;
echo -en " — $SECONDS s\n";

echo "Installing node_modules dependencies...";

NOOP=$(mktemp /tmp/noop_make.XXXXX)
cat > $NOOP <<EOF
#!/bin/sh
# echo "Ignore 'make' because we want to disable node-gyp builds"
EOF
chmod +x $NOOP;
$NOOP one two three;

cd ./nodejs-assets/nodejs-project && npm_config_make=$NOOP npm install --no-optional --silent;

# For more details on this, read issue #398:
SECONDS=0
echo -en "Removing problematic transitive dependencies...";
cd node_modules && rm -rf chokidar fsevents && cd ../../..;
echo -en " — $SECONDS s\n";

SECONDS=0
echo -en "Updating package-lock.json...";
cp ./nodejs-assets/nodejs-project/package-lock.json ./src/backend/package-lock.json
echo -en " — $SECONDS s\n";

SECONDS=0
echo -en "Patch some dependencies...";
./tools/patch-backend-ssb-server ./nodejs-assets/nodejs-project;
echo -en " — $SECONDS s\n";
