#!/bin/bash
set -eEu -o pipefail
shopt -s extdebug
IFS=$'\n\t'
trap 'onFailure $?' ERR

function onFailure() {
  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
  exit 1
}


echo "Compiling TypeScript...";
npm run lib;

echo "Setting up...";
rm -rf ./nodejs-assets/nodejs-project;
mkdir -p ./nodejs-assets/nodejs-project;
if [ -f ./nodejs-assets/BUILD_NATIVE_MODULES.txt ]
then
  echo "Build Native Modules on";
else
  echo '1' >./nodejs-assets/BUILD_NATIVE_MODULES.txt;
  echo "Set Build Native Modules on";
fi
cp -r ./lib/nodejs-project ./nodejs-assets;
cp ./src/nodejs-project/package.json ./nodejs-assets/nodejs-project;
cp ./src/nodejs-project/package-lock.json ./nodejs-assets/nodejs-project;
rm ./nodejs-assets/nodejs-project/**/*.js.map;

echo "Installing dependencies...";
cd ./nodejs-assets/nodejs-project && npm i && cd ../..;

echo "Updating package-lock.json";
cp ./nodejs-assets/nodejs-project/package-lock.json ./src/nodejs-project/package-lock.json

echo "Patch (in preprocessor style) some dependencies...";
./tools/patch-rnnodeapp-scuttlebot ./nodejs-assets/nodejs-project;

echo "Done.";
