#!/bin/bash
set -eEu -o pipefail
shopt -s extdebug
IFS=$'\n\t'
trap 'onFailure $?' ERR

function onFailure() {
  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
  exit 1
}


npm run lib;

node node_modules/react-native/local-cli/cli.js bundle \
  --dev false \
  --platform android \
  --entry-file worker.js \
  --assets-dest ./android/app/src/main/res/ \
  --bundle-output ./android/app/src/main/assets/worker.bundle
