#!/bin/bash

echo "Compiling TypeScript...";
npm run lib;

echo "Setting up...";
rm -rf ./rnnodeapp;
mkdir -p ./rnnodeapp;
cp -r ./lib/rnnodeapp ./;
cp ./src/rnnodeapp/package.json ./rnnodeapp/;
rm ./rnnodeapp/*.js.map;

echo "Installing dependencies...";
cd ./rnnodeapp && npm i && cd ..;

echo "Setting up folder for native bindings...";
mv ./rnnodeapp/node_modules/leveldown-android-prebuilt/compiled ./rnnodeapp/compiled;

echo "Patch (in preprocessor style) some dependencies...";
./tools/patch-rnnodeapp-scuttlebot ./rnnodeapp

echo "Minifying...";
$(npm bin)/noderify \
  --replace.chloride=sodium-browserify-tweetnacl \
  --replace.sodium-chloride=sodium-browserify-tweetnacl \
  --replace.node-extend=xtend \
  --replace.leveldown=leveldown-android-prebuilt \
  ./rnnodeapp/index.js > ./rnnodeapp/_index.js;
rm ./rnnodeapp/index.js;
mv ./rnnodeapp/_index.js ./rnnodeapp/index.js;

echo "Cleaning up...";
rm -rf ./rnnodeapp/node_modules;

echo "Bundling into Android...";
$(npm bin)/react-native-node insert ./rnnodeapp

echo "Done."
