#!/bin/bash
set -eEu -o pipefail
shopt -s extdebug
IFS=$'\n\t'
trap 'onFailure $?' ERR

function onFailure() {
  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
  exit 1
}

mkdir -p ../dat-release-all
mkdir -p ../dat-release-latest
cp android/app/build/outputs/apk/release/app-release.apk ../dat-release-all/manyverse-$(cat package.json | $(npm bin)/jase version).apk
cp android/app/build/outputs/apk/release/app-release.apk ../dat-release-latest/app-release.apk
