#!/bin/bash

# Any copyright is dedicated to the Public Domain.
# http://creativecommons.org/publicdomain/zero/1.0/

set -eEu -o pipefail
shopt -s extdebug
IFS=$'\n\t'
trap 'onFailure $?' ERR

function onFailure() {
  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
  exit 1
}

echo -en "Bundling with noderify...";
cd ./desktop/nodejs-project;
# Why some packages are filter'd or replaced:
#   electron: we want nodejs-mobile to load its native bindings
#   bufferutil: because we want nodejs-mobile to load its native bindings
#   utf-8-validate: because we want nodejs-mobile to load its native bindings
$(npm bin)/noderify \
  --replace.node-extend=xtend \
  --replace.multiserver/plugins/net=staltz-multiserver/plugins/net \
  --replace.non-private-ip=non-private-ip-android \
  --filter=rn-bridge \
  --filter=electron \
  --filter=bufferutil \
  --filter=utf-8-validate \
  index.js > _index.js;
rm index.js; mv _index.js index.js;
rm multiserver.js;
rm restore.js;
rm ssb.js;
rm -rf plugins;
cd ../..;
echo -en " done.\n";
