#!/bin/bash
set -eEu -o pipefail
shopt -s extdebug
IFS=$'\n\t'
trap 'onFailure $?' ERR

function onFailure() {
  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
  exit 1
}

echo "Building native modules for armeabi-v7a...";
cd android;
if [ -f ./gradlew ]
then
  ./gradlew nodejs-mobile-react-native:GenerateNodeNativeAssetsListsarmeabi-v7a
else
  gradle nodejs-mobile-react-native:GenerateNodeNativeAssetsListsarmeabi-v7a
fi
cd ..;
echo "";

echo -en "Minifying with noderify...";
cd ./nodejs-assets/nodejs-project;
$(npm bin)/noderify \
  --replace.bindings=bindings-noderify-nodejs-mobile \
  --replace.node-extend=xtend \
  --replace.utp-native=utp-native-no-prebuild \
  --filter=rn-bridge \
  index.js > _index.js;
rm index.js;
mv _index.js index.js;
cd ../..;
echo -en " done.\n";

echo -en "Replacing node_modules folder...";
rm -rf ./nodejs-assets/nodejs-project/node_modules;
cp -r ./android/build/nodejs-native-assets/nodejs-native-assets-armeabi-v7a/node_modules ./nodejs-assets/nodejs-project;
echo -en " done.\n";

echo -en "Removing other unused files...";
rm ./nodejs-assets/nodejs-project/package-lock.json
# make a list of things to delete then delete them
# `-exec rm -rf {} \;` confuses find because the recursion can no longer find a step (depth-first traversal (-d) would also work)
# GNU find and modern BSD/macOS find have a `-delete` operator
find ./nodejs-assets/nodejs-project \
  -type d \
  \( \
    -name "darwin-x64" \
    -o -name "win32-ia32" \
    -o -name "win32-x64" \
  \) \
  -print0 | xargs -0 rm -rf # delete everything in the list
echo -en " done.\n";
