#!/bin/bash

# Any copyright is dedicated to the Public Domain.
# http://creativecommons.org/publicdomain/zero/1.0/

set -eEu -o pipefail
shopt -s extdebug
IFS=$'\n\t'
trap 'onFailure $?' ERR

function onFailure() {
  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
  exit 1
}

SECONDS=0
echo -en "Removing unused files meant for macOS or Windows, etc...";
# make a list of things to delete then delete them
# `-exec rm -rf {} \;` confuses find because the recursion can no longer find a step (depth-first traversal (-d) would also work)
# GNU find and modern BSD/macOS find have a `-delete` operator
find ./nodejs-assets/nodejs-project/node_modules \
  -type d \
  \( \
    -name "darwin-x64" \
    -o -name "win32-ia32" \
    -o -name "win32-x64" \
  \) \
  -print0 | xargs -0 rm -rf # delete everything in the list
find ./nodejs-assets/nodejs-project/node_modules \
  -type f \
  \( \
    -name "electron-napi.node" \
  \) \
  -print0 | xargs -0 rm -rf # delete everything in the list
echo -en " — $SECONDS s\n";

# "NDK_ARCH;NODEJS_ARCH"
declare -a archs=(
  "armeabi-v7a;arm"
  "arm64-v8a;arm64"
  # "x86;x86"
  # "x86_64;x64"
)

cd android;
if [ -f ./gradlew ]
then
  GRADLE_EXEC="./gradlew"
else
  GRADLE_EXEC="gradle"
fi
echo $GRADLE_EXEC;
for entry in "${archs[@]}"
do
  IFS=";" read -r -a arr <<< "${entry}" # entry.split(';')
  arch="${arr[0]}"

  echo "Building native modules for $arch...";
  $GRADLE_EXEC nodejs-mobile-react-native:GenerateNodeNativeAssetsLists$arch
done
cd ..;
echo "";

SECONDS=0
echo -en "Minifying with noderify...";
cd ./nodejs-assets/nodejs-project;
# Why some packages are filter'd:
#   rn-bridge: this is not an npm package, it's just a nodejs-mobile shortcut
#   bl: we didn't use it, and bl@0.8.x has security vulnerabilities
#   braces: we didn't use it, and braces@1.8.x has vulnerabilities
$(npm bin)/noderify \
  --replace.bindings=bindings-noderify-nodejs-mobile \
  --replace.node-extend=xtend \
  --replace.multiserver/plugins/net=staltz-multiserver/plugins/net \
  --replace.non-private-ip=non-private-ip-android \
  --replace.utp-native=utp-native-nodejs-mobile \
  --filter=rn-bridge \
  --filter=bl \
  --filter=braces \
  --filter=bufferutil \
  --filter=utf-8-validate \
  index.js > _index.js;
rm index.js;
mv _index.js index.js;
cd ../..;
echo -en " — $SECONDS s\n";

SECONDS=0
echo -en "Removing node_modules folder and package-lock.json...";
rm -rf ./nodejs-assets/nodejs-project/node_modules;
rm ./nodejs-assets/nodejs-project/package-lock.json
echo -en " — $SECONDS s\n";
