#!/bin/bash

# Any copyright is dedicated to the Public Domain.
# http://creativecommons.org/publicdomain/zero/1.0/

set -eEu -o pipefail
shopt -s extdebug
IFS=$'\n\t'
trap 'onFailure $?' ERR

function onFailure() {
  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
  exit 1
}

echo -en "Minifying with noderify...";
cd ./desktop/nodejs-project;
$(npm bin)/noderify \
  --replace.node-extend=xtend \
  --replace.multiserver/plugins/net=staltz-multiserver/plugins/net \
  --replace.non-private-ip=non-private-ip-android \
  index.js > _index.js;
rm index.js;
mv _index.js index.js;
cd ../..;
echo -en " done.\n";
