#!/usr/bin/env node

/* Any copyright is dedicated to the Public Domain.
 * http://creativecommons.org/publicdomain/zero/1.0/ */

const fs = require('fs');
const path = require('path');

const backendPath = process.argv[2];
const ssbDbPath = path.join(backendPath, 'node_modules/ssb-db');

if (!fs.existsSync(ssbDbPath)) {
  throw new Error('Cannot find file ssb-db/index.js to patch');
}

const indexjsPath = path.join(ssbDbPath, './index.js');
const prevContent = fs.readFileSync(indexjsPath, 'utf-8');

const dirname = path.dirname(indexjsPath);

function readMarkdownCompileTime(relPath) {
  return fs
    .readFileSync(path.join(dirname, relPath), 'utf-8')
    .replace(/\`\`\`/g, '')
    .replace(/\`/g, '"');
}

const nextContent = prevContent.replace(
  `fs.readFileSync(path.join(__dirname, 'api.md'), 'utf-8')`,
  `\`${readMarkdownCompileTime('api.md')}\``,
);

fs.writeFileSync(indexjsPath, nextContent, 'utf-8');
