#!/bin/bash
set -eEu -o pipefail
shopt -s extdebug
IFS=$'\n\t'
trap 'onFailure $?' ERR

function onFailure() {
  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
  exit 1
}

adb uninstall se.manyver
$(npm bin)/appium --port 4995 > appium.log & echo $! > appium-server.pid
sleep 5
$(npm bin)/tape e2e/index.js | tap-spec
if ps -p $(cat appium-server.pid)> /dev/null; then
  kill -KILL $(cat appium-server.pid)
fi
rm appium-server.pid
rm appium.log