# SPDX-FileCopyrightText: 2021-2023 The Manyverse Authors
#
# SPDX-License-Identifier: Unlicense

name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  license-check:
    name: License check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

  typescript:
    name: TypeScript compilation
    runs-on: ubuntu-latest
    needs: license-check
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.17.x

      - name: npm install
        run: npm install

      - name: TypeScript compilation
        run: npm run lib
