# SPDX-FileCopyrightText: 2021-2022 The Manyverse Authors
#
# SPDX-License-Identifier: Unlicense

name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  license-check:
    name: License check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

  test-e2e-desktop:
    name: End-to-end tests on desktop
    runs-on: ubuntu-latest
    needs: license-check
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: npm install
        run: npm install

      - run: npm run test-e2e-desktop
